name: Test
on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PyO3/maturin
          ref: main
          path: maturin
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: maturin build
        uses: ./
        with:
          rust-toolchain: ${{ matrix.toolchain }}
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
      - name: maturin build universal2
        if: matrix.os == 'macos-latest'
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml --universal2
      - name: check maturin in PATH
        run: maturin --version
      - name: maturin build manylinux2010
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
          manylinux: '2010'

  test-manylinux:
    name: Manylinux Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [
          { manylinux: '2010', target: 'x86_64-unknown-linux-gnu', container: 'quay.io/pypa/manylinux2010_x86_64' },
          { manylinux: '2010', target: 'i686-unknown-linux-gnu', container: 'quay.io/pypa/manylinux2010_i686' },
          # { manylinux: '2014', target: 'aarch64-unknown-linux-gnu', container: 'messense/manylinux2014-cross:aarch64' },
          # { manylinux: '2014', target: 'armv7-unknown-linux-gnueabihf', container: 'messense/manylinux2014-cross:armv7' },
        ]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PyO3/maturin
          ref: main
          path: maturin
      - name: maturin build
        uses: ./
        with:
          maturin-version: '0.10.2'
          rust-toolchain: ${{ matrix.toolchain }}
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
          manylinux: ${{ matrix.platform.manylinux }}
          target: ${{ matrix.platform.target }}
          container: ${{ matrix.platform.container }}
