name: Test
on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    needs: [lint]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PyO3/maturin
          ref: main
          path: maturin
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: maturin build
        uses: ./
        with:
          rust-toolchain: ${{ matrix.toolchain }}
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
      - name: maturin build universal2
        if: matrix.os == 'macos-latest'
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml --universal2
      - name: check maturin in PATH
        run: maturin --version
      - name: maturin build manylinux2010
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
          manylinux: '2010'
      - name: maturin build manylinux off
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
          manylinux: 'off'
      - name: maturin build container off
        uses: ./
        with:
          args: -m maturin/test-crates/pyo3-mixed/Cargo.toml
          manylinux: '2_24'
          container: 'off'

  test-manylinux:
    name: Manylinux Test Suite
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        platform: [
          {
            manylinux: '2010',
            target: 'x86_64-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-mixed'
          },
          {
            manylinux: '2010',
            target: 'i686-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-mixed'
          },
          {
            manylinux: '2014',
            target: 'aarch64-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-pure'  # abi3
          },
          {
            manylinux: '2014',
            target: 'armv7-unknown-linux-gnueabihf',
            test-crate: 'maturin/test-crates/pyo3-pure'  # abi3
          },
          {
            manylinux: '2014',
            target: 'powerpc64le-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-mixed'
          },
          {
            manylinux: '2_24',
            target: 'powerpc64le-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-mixed'
          },
          {
            manylinux: '2014',
            target: 's390x-unknown-linux-gnu',
            test-crate: 'maturin/test-crates/pyo3-mixed'
          },
        ]
        toolchain: [stable, nightly]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PyO3/maturin
          ref: main
          path: maturin
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: maturin build
        uses: ./
        env:
          RUST_BACKTRACE: '1'
          PYO3_CROSS_LIB_DIR: '/opt/python/cp38-cp38/lib'
        with:
          maturin-version: 'v0.10.5-beta.4'
          container: ${{ matrix.platform.container }}
          rust-toolchain: ${{ matrix.toolchain }}
          args: -m ${{ matrix.platform.test-crate }}/Cargo.toml -i python3.8 --no-sdist
          manylinux: ${{ matrix.platform.manylinux }}
          target: ${{ matrix.platform.target }}
